# Generated by Django 5.0.4 on 2024-04-28 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prenda',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('marca', models.CharField(choices=[('Bleu Ciel', 'Bleu Ciel'), ('Down Under', 'Down Under'), ('Drake Urban', 'Drake Urban'), ('Effects', 'Effects'), ('Esenzia', 'Esenzia'), ('Goated', 'Goated'), ('Half Studios', 'Half Studios'), ('Heartbreak Hotel', 'Heartbreak Hotel'), ('Horizon Studios', 'Horizon Studios'), ('Humpier', 'Humpier'), ('Jesper', 'Jesper'), ('Les Gars', 'Les Gars'), ('NWHR', 'NWHR'), ('Old School', 'Old School'), ('Otherlife', 'Otherlife'), ('Shameless Collective', 'Shameless Collective'), ('Signal', 'Signal'), ('Sonder Stories', 'Sonder Stories'), ('Stooner', 'Stooner'), ('Takkra', 'Takkra')], max_length=50)),
                ('descripcion', models.TextField(max_length=100)),
                ('talla', models.CharField(choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], max_length=3)),
                ('cantidad_stock', models.PositiveIntegerField(default=0)),
                ('material', models.CharField(choices=[('Algodón', 'Algodón'), ('Poliéster', 'Poliéster'), ('Lino', 'Lino'), ('Lana', 'Lana'), ('Seda', 'Seda'), ('Nylon', 'Nylon'), ('Lycra', 'Lycra')], max_length=50)),
                ('precio_original', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_rebajado', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('fecha_novedad', models.DateTimeField(auto_now_add=True)),
                ('tipo_prenda', models.CharField(choices=[('Abrigos y Chaquetas', 'Abrigos y Chaquetas'), ('Bañadores', 'Bañadores'), ('Bolsas', 'Bolsas'), ('Bolsos', 'Bolsos'), ('Braga', 'Braga'), ('Calcetines', 'Calcetines'), ('Calzado', 'Calzado'), ('Camisas', 'Camisas'), ('Camisetas', 'Camisetas'), ('Camisetas de Tirantes', 'Camisetas de Tirantes'), ('Camisetas Manga Larga', 'Camisetas Manga Larga'), ('Chalecos', 'Chalecos'), ('Faldas', 'Faldas'), ('Gorras', 'Gorras'), ('Gorros', 'Gorros'), ('Jerséis', 'Jerséis'), ('Pantalón Corto', 'Pantalón Corto'), ('Pantalón Largo', 'Pantalón Largo'), ('Polares', 'Polares'), ('Polo Manga Larga', 'Polo Manga Larga'), ('Polos', 'Polos'), ('Sudaderas con Capucha', 'Sudaderas con Capucha'), ('Sudaderas con Cremallera', 'Sudaderas con Cremallera'), ('Sudaderas sin Capucha', 'Sudaderas sin Capucha'), ('Top', 'Top'), ('Vestidos', 'Vestidos'), ('Zapatillas', 'Zapatillas')], max_length=50)),
                ('color', models.CharField(choices=[('Amarillo', 'Amarillo'), ('Azul', 'Azul'), ('Azul Celeste', 'Azul Celeste'), ('Azul Eléctrico', 'Azul Eléctrico'), ('Azul Marino', 'Azul Marino'), ('Azul Oscuro', 'Azul Oscuro'), ('Azul Turquesa', 'Azul Turquesa'), ('Beige', 'Beige'), ('Blanco', 'Blanco'), ('Blanco Roto', 'Blanco Roto'), ('Blanco y Negro', 'Blanco y Negro'), ('Caqui', 'Caqui'), ('Coral', 'Coral'), ('Granate', 'Granate'), ('Gris', 'Gris'), ('Gris Oscuro', 'Gris Oscuro'), ('Lila', 'Lila'), ('Marrón', 'Marrón'), ('Multicolor', 'Multicolor'), ('Naranja', 'Naranja'), ('Negro', 'Negro'), ('Oro', 'Oro'), ('Plata', 'Plata'), ('Rojo', 'Rojo'), ('Rosa', 'Rosa'), ('Verde', 'Verde'), ('Verde Oscuro', 'Verde Oscuro')], max_length=20)),
                ('genero', models.CharField(choices=[('Hombre', 'Hombre'), ('Mujer', 'Mujer'), ('Niño', 'Niño'), ('Niña', 'Niña')], max_length=6)),
            ],
            options={
                'verbose_name': 'Prenda',
                'verbose_name_plural': 'Prendas',
            },
        ),
    ]
