# Generated by Django 5.0.6 on 2024-05-23 20:12

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prendaApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='contenido',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True),
        ),
    ]
