# Generated by Django 5.0.4 on 2024-04-28 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PrendaApp', '0002_alter_prenda_precio_rebajado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prenda',
            name='precio_rebajado',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
