# Generated by Django 5.0.4 on 2024-04-28 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PrendaApp', '0004_remove_prenda_color_remove_prenda_genero_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prenda',
            name='color',
            field=models.CharField(choices=[('Amarillo', 'Amarillo'), ('Azul', 'Azul'), ('Azul Celeste', 'Azul Celeste'), ('Azul Eléctrico', 'Azul Eléctrico'), ('Azul Marino', 'Azul Marino'), ('Azul Oscuro', 'Azul Oscuro'), ('Azul Turquesa', 'Azul Turquesa'), ('Beige', 'Beige'), ('Blanco', 'Blanco'), ('Blanco Roto', 'Blanco Roto'), ('Blanco y Negro', 'Blanco y Negro'), ('Caqui', 'Caqui'), ('Coral', 'Coral'), ('Granate', 'Granate'), ('Gris', 'Gris'), ('Gris Oscuro', 'Gris Oscuro'), ('Lila', 'Lila'), ('Marrón', 'Marrón'), ('Multicolor', 'Multicolor'), ('Naranja', 'Naranja'), ('Negro', 'Negro'), ('Oro', 'Oro'), ('Plata', 'Plata'), ('Rojo', 'Rojo'), ('Rosa', 'Rosa'), ('Verde', 'Verde'), ('Verde Oscuro', 'Verde Oscuro')], default='Blanco', max_length=20),
        ),
        migrations.AddField(
            model_name='prenda',
            name='genero',
            field=models.CharField(choices=[('Hombre', 'Hombre'), ('Mujer', 'Mujer'), ('Niño', 'Niño'), ('Niña', 'Niña')], default='Hombre', max_length=6),
        ),
        migrations.AddField(
            model_name='prenda',
            name='tipo_prenda',
            field=models.CharField(choices=[('Abrigos y Chaquetas', 'Abrigos y Chaquetas'), ('Bañadores', 'Bañadores'), ('Bolsas', 'Bolsas'), ('Bolsos', 'Bolsos'), ('Braga', 'Braga'), ('Calcetines', 'Calcetines'), ('Calzado', 'Calzado'), ('Camisas', 'Camisas'), ('Camisetas', 'Camisetas'), ('Camisetas de Tirantes', 'Camisetas de Tirantes'), ('Camisetas Manga Larga', 'Camisetas Manga Larga'), ('Chalecos', 'Chalecos'), ('Faldas', 'Faldas'), ('Gorras', 'Gorras'), ('Gorros', 'Gorros'), ('Jerséis', 'Jerséis'), ('Pantalón Corto', 'Pantalón Corto'), ('Pantalón Largo', 'Pantalón Largo'), ('Polares', 'Polares'), ('Polo Manga Larga', 'Polo Manga Larga'), ('Polos', 'Polos'), ('Sudaderas con Capucha', 'Sudaderas con Capucha'), ('Sudaderas con Cremallera', 'Sudaderas con Cremallera'), ('Sudaderas sin Capucha', 'Sudaderas sin Capucha'), ('Top', 'Top'), ('Vestidos', 'Vestidos'), ('Zapatillas', 'Zapatillas')], default='Camisetas', max_length=50),
        ),
        migrations.AlterField(
            model_name='prenda',
            name='precio_rebajado',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
