# Generated by Django 5.0.4 on 2024-04-28 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prenda', '0002_prenda_delete_ropa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prenda',
            name='precio_rebajado',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
